version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: vaibhav
      POSTGRES_PASSWORD: vaibhav
      POSTGRES_DB: vaibhav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
  
networks:
  app_network:
    driver: bridge