version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

  backend:
    image: vaibhavdawane/backend-web3
    container_name: my-backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - my-network
    depends_on:
      - postgres
    restart: always
    ports:
      - "3000:3000"

  frontend:
    image: vaibhavdawane/frontend-web3
    container_name: my-frontend
    networks:
      - my-network
    depends_on:
      - backend
    restart: always
    ports:
      - "8000:8000"
    
volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
